spring:
  application:
    name: Online Voting System

  datasource:
    url: jdbc:postgresql://localhost:5432/votehub
    username: leo
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true
    enabled: true

logging:
  level:
#    root: debug
    org:
      flyway: debug

jwt:
  secret-key: "kungikawaymasayatumawahahahakungikawaymasayatumawakahahaha1230987"
  expiration-day: 7